### ISSUE TITLE
wrong conf dir is used

### ISSUE THREAD

**Issue by sattotal** [GruberMarkus/Build-OSCamForWindows#1]
The default config directory is: '/usr/local/etc' (see source file README.build) 
on Win OS this directory doesn't exit  
please add to the make line f.e.  'make CONF_DIR=./'

Thx

**Comment by GruberMarkus** [comment]
Thanks for your feedback.

Commit c4139232a4b248a30fe9af184f35b9921f8d8814 solves the problem.
