### ISSUE TITLE
i can't build

### ISSUE THREAD

**Issue by iospoisson** [GruberMarkus/Build-OSCamForWindows#2]
Downloading latest Cygwin Portable Installer ... done.

Updating Cygwin Portable ... done. Exit code 0.

Downloading latest oscam source code and compiling it ... Set-Content: C:\Users\iospoisson\Documents\oscam\Build-OSCamForWindows.ps1:202
Line |
 202 |  … ).GetBytes(($x -ireplace "`r`n", "`n") + "`n") -Encoding Byte -Path ' …
     |                                                             ~~~~
     | Cannot process argument transformation on parameter 'Encoding'. 'Byte' is not a supported encoding
     | name. For information on defining a custom encoding, see the documentation for the
     | Encoding.RegisterProvider method. (Parameter 'name')

Move-Item: C:\Users\iospoisson\Documents\oscam\Build-OSCamForWindows.ps1:204
Line |
 204 |  Move-Item -Path ".\cygwin\tmp\oscam-buildlog.txt" -Destination ".\cyg …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot create a file when that file already exists.

Get-ChildItem: C:\Users\iospoisson\Documents\oscam\Build-OSCamForWindows.ps1:205
Line |
 205 |  … ationPath ((Get-ChildItem ".\cygwin\home\root\oscam-zip\*.zip" | Sele …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path
     | 'C:\Users\iospoisson\AppData\Local\Temp\Build-OSCamForWindows\cygwin\home\root\oscam-zip' because it
     | does not exist.

Compress-Archive: C:\Users\iospoisson\Documents\oscam\Build-OSCamForWindows.ps1:205
Line |
 205 |  … inationPath ((Get-ChildItem ".\cygwin\home\root\oscam-zip\*.zip" | Se …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'DestinationPath'. The argument is null or empty. Provide an
     | argument that is not null or empty, and then try the command again.

done. Exit code 0.

Copying compiled binaries and dependent Cygwin DLLs ... Get-ChildItem: C:\Users\iospoisson\Documents\oscam\Build-OSCamForWindows.ps1:229
Line |
 229 |      $x = (Get-ChildItem -Path (Join-Path -Path $tempPath -ChildPath " …
     |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path
     | 'C:\Users\IOSPOI~1\AppData\Local\Temp\Build-OSCamForWindows\cygwin\home\root\oscam-zip' because it
     | does not exist.

Split-Path: C:\Users\iospoisson\Documents\oscam\Build-OSCamForWindows.ps1:230
Line |
 230 |  … PSScriptRoot -ChildPath "oscam-zip") -ChildPath (Split-Path $x -Leaf)
     |                                                                ~~
     | Cannot bind argument to parameter 'Path' because it is null.

Copy-Item: C:\Users\iospoisson\Documents\oscam\Build-OSCamForWindows.ps1:232
Line |
 232 |      Copy-Item -Path $x -Destination $y -Force
     |                      ~~
     | Cannot bind argument to parameter 'Path' because it is null.

Expand-Archive: C:\Users\iospoisson\Documents\oscam\Build-OSCamForWindows.ps1:233
Line |
 233 |      Expand-Archive -Path $y -DestinationPath (Join-Path -Path $PSScri …
     |                           ~~
     | Cannot validate argument on parameter 'Path'. The argument is null or empty. Provide an argument that
     | is not null or empty, and then try the command again.

done.

**Comment by GruberMarkus** [comment]
Build with PowerShell 5, not a newer version.

**Comment by GruberMarkus** [comment]
Fixed in https://github.com/GruberMarkus/Build-OSCamForWindows/commit/7c7b03714cd4d0bc7396f814fcd63cbc1135cf61, waiting for your test results.

**Comment by iospoisson** [comment]
I can confirm issue has been fixed ,thanks
